// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateFolders(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateFolders'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateFoldersV2(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFoldersV2'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigField(arg1) {
  return window['go']['main']['App']['GetConfigField'](arg1);
}

export function GetCopyFolderDialog() {
  return window['go']['main']['App']['GetCopyFolderDialog']();
}

export function GetExcelFileDialog() {
  return window['go']['main']['App']['GetExcelFileDialog']();
}

export function GetFileDialog() {
  return window['go']['main']['App']['GetFileDialog']();
}

export function GetLoadConfigPath() {
  return window['go']['main']['App']['GetLoadConfigPath']();
}

export function GetTargetFolderDialog() {
  return window['go']['main']['App']['GetTargetFolderDialog']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWordFileDialog() {
  return window['go']['main']['App']['GetWordFileDialog']();
}

export function NeedsAdminPrivileges() {
  return window['go']['main']['App']['NeedsAdminPrivileges']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ReadConfig(arg1) {
  return window['go']['main']['App']['ReadConfig'](arg1);
}

export function RestartApplication(arg1, arg2) {
  return window['go']['main']['App']['RestartApplication'](arg1, arg2);
}

export function SaveConfigDialog() {
  return window['go']['main']['App']['SaveConfigDialog']();
}

export function SendNotification(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3, arg4);
}

export function SetConfigField(arg1, arg2) {
  return window['go']['main']['App']['SetConfigField'](arg1, arg2);
}

export function Update(arg1) {
  return window['go']['main']['App']['Update'](arg1);
}

export function UpdateAsAdmin(arg1) {
  return window['go']['main']['App']['UpdateAsAdmin'](arg1);
}
